package main

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/nilnoun/protoc-gen-error/errors"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

const (
	fmtPackage = protogen.GoImportPath("fmt")
)

var errorsPackage *protogen.GoImportPath
var enCases = cases.Title(language.AmericanEnglish, cases.NoLower)

func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Enums) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_errors.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-error. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.QualifiedGoIdent(errorsPackage.Ident(""))
	g.QualifiedGoIdent(fmtPackage.Ident(""))
	generateFileContent(gen, file, g)
	return g
}

func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	if len(file.Enums) == 0 {
		return
	}
	g.P()
	index := 0
	for _, enum := range file.Enums {
		if !genErrorsReason(gen, file, g, enum) {
			index++
		}
	}
	// If all enums do not contain 'errors.code', the current file is skipped
	if index == 0 {
		g.Skip()
	}
}

func genErrorsReason(_ *protogen.Plugin, _ *protogen.File, g *protogen.GeneratedFile, enum *protogen.Enum) bool {
	var ew errorWrapper
	for _, v := range enum.Values {
		code := proto.GetExtension(v.Desc.Options(), errors.E_Code).(int32)
		httpCode := proto.GetExtension(v.Desc.Options(), errors.E_HttpCode).(int32)
		message := proto.GetExtension(v.Desc.Options(), errors.E_Message).(string)

		comment := v.Comments.Leading.String()
		if comment == "" {
			comment = v.Comments.Trailing.String()
		}

		if httpCode <= 100 || httpCode >= 599 {
			panic(fmt.Sprintf("Enum '%s' http_code range must be between 100 and 599", string(v.Desc.Name())))
		}
		if code <= 0 {
			panic(fmt.Sprintf("Enum '%s' code range must be greater than 0", string(v.Desc.Name())))
		}

		err := &errorInfo{
			Name:       string(enum.Desc.Name()),
			Value:      string(v.Desc.Name()),
			CamelValue: case2Camel(string(v.Desc.Name())),
			Code:       int(code),
			HTTPCode:   int(httpCode),
			Message:    message,
			Comment:    comment,
			HasComment: len(comment) > 0,
		}
		ew.Errors = append(ew.Errors, err)
	}
	if len(ew.Errors) == 0 {
		return true
	}
	g.P(ew.execute())

	return false
}

func case2Camel(name string) string {
	if !strings.Contains(name, "_") {
		if name == strings.ToUpper(name) {
			name = strings.ToLower(name)
		}
		return enCases.String(name)
	}
	strList := strings.Split(name, "_")
	words := make([]string, 0, len(strList))
	for _, w := range strList {
		hasLower := false
		for _, r := range w {
			if unicode.IsLower(r) {
				hasLower = true
				break
			}
		}
		if !hasLower {
			w = strings.ToLower(w)
		}
		w = enCases.String(w)
		words = append(words, w)
	}

	return strings.Join(words, "")
}
